wandb:
    entity: null

experiment:
    project: "muse"
    name: "imagenet-vqgan-training"
    output_dir: "imagenet-vqgan-training"
    max_train_examples: 1281167 # total number of imagenet examples
    max_eval_examples: 12800
    save_every: 1000
    eval_every: 1000
    generate_every: 1000
    log_every: 30
    log_grad_norm_every: 500
    resume_from_checkpoint: False
    resume_lr_scheduler: True

model:
    vq_model:
        type: "taming_vqgan"
        pretrained: "openMUSE/vqgan-f16-8192-laion"
    gradient_checkpointing: True
    enable_xformers_memory_efficient_attention: True


dataset:
    type: "classification"
    params:
        train_shards_path_or_url: "pipe:aws s3 cp s3://s-laion/muse-imagenet/imagenet-train-{000000..000320}.tar -"
        eval_shards_path_or_url: "pipe:aws s3 cp s3://s-laion/muse-imagenet/imagenet-val-{000000..000012}.tar -"
        imagenet_class_mapping_path: "/fsx/Isamu/data/imagenet-class-mapping.json"
        dataset.params.validation_prompts_file: null
        batch_size: ${training.batch_size}
        shuffle_buffer_size: 1000
        num_workers: 4
        resolution: 256
        pin_memory: True
        persistent_workers: True
    preprocessing:
        max_seq_length: 16
        resolution: 256
        center_crop: True
        random_flip: False
discriminator:
    dim: 64
    channels: 3
    groups: 32
    init_kernel_size: 5
    kernel_size: 3
    act: "silu"
    discr_layers: 4
optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 1e-4
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8
        discr_learning_rate: 1e-4


lr_scheduler:
    scheduler: "constant_with_warmup"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 1000


training:
    gradient_accumulation_steps: 2
    batch_size: 64
    mixed_precision: "no"
    enable_tf32: True
    use_ema: False
    seed: 9345104
    max_train_steps: 200000
    overfit_one_batch: False
    cond_dropout_prob: 0.1
    min_masking_rate: 0.0
    label_smoothing: 0.0
    max_grad_norm: null
    guidance_scale: 2.0
    generation_timesteps: 8
    # related to vae code sampling
    use_soft_code_target: False
    use_stochastic_code: False
    soft_code_temp: 1.0
    timm_discriminator_backend: "vgg19"
    timm_disc_layers: "features|pre_logits|head"
    timm_discr_offset: 0
    vae_loss: "l2"
    num_validation_log: 4
    discriminator_warmup: 10000
